# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 7

# Dependencies
before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: composer test